set(CMAKE_SYSTEM Generic)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CROSSCOMPILING 1)

set(CMAKE_LINK_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")

set(CMAKE_C_COMPILER arm-none-eabi-gcc)
set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)

set(STARTUP_SOURCES stm32f10x/startup_stm32f10x.s stm32f10x/system_stm32f10x.c)
set(STARTUP_CFLAGS -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER)
set(LINKER_SCRIPT stm32f10x/stm32f103_128k.ld)
